### ISSUE TITLE
 ◟ Logging in, please wait...          Error occured in login

### ISSUE THREAD

**Issue by hariharan-dev** [riazXrazor/udemy-dl#39] opened 2018-06-12 17:01 UTC
I`m getting this error when I try to download. Can you help?

**Comment by miguelcarrasco** [comment] 2018-06-13 19:56
Me too, it looks that it's an issue regarding "human verification" or some cookie validations.

**Comment by Proinfinto** [comment] 2018-06-22 11:39
The error is still continuing.

**Comment by im-jbaxter** [comment] 2018-06-25 10:04
Was working fine a few days ago, but now I'm also getting login issues.

**Comment by riazXrazor** [comment] 2018-06-25 11:46
sorry guys, there is a captcha being returned, when the login api is being called, currently i am trying, no luck so far :(

**Comment by hariharan-dev** [comment] 2018-06-25 17:05
Please update us when fixed

**Comment by Proinfinto** [comment] 2018-06-26 07:15
@riazXrazor we trust you, we will improve soon ;)

**Comment by kaungdev** [comment] 2018-06-28 09:20
thank u so much for trying

**Comment by ramojej** [comment] 2018-06-30 04:50
I'm having the same error.

**Comment by c0ppo** [comment] 2018-07-05 07:42
Same issue here... Any luck with fixing this?
And thanks for trying 👍

**Comment by lucis** [comment] 2018-07-08 17:00
Would it be possible to make a frontend version? The user would login and execute a javascript in its Console. I've done the same in order to download images...

**Comment by lucis** [comment] 2018-07-08 19:16
Pythons's udemy-dl was able to solve it requiring the cookies of a verified request in Udemy's website. I think that's a viable solution

**Comment by riazXrazor** [comment] 2018-07-09 04:03
Yup I was doing the same thing, ws saving the cookie after login which ws
verified. Now whenever the script requests the login udemy server seems to
kno that is an automated scripts n sends a captcha instead.

**Comment by riazXrazor** [comment] 2018-07-24 09:35
hi guys, i hv push a fix and released a new version, plz can u check if the issue is fixed.

**Comment by kevenleone** [comment] 2018-07-24 11:25
@riazXrazor good morning, it's working perfectly, thanks ^_^

**Comment by bodaay** [comment] 2018-07-25 14:03
not working for me

by the way, the python version https://github.com/r0oth3x49/udemy-dl
is working fine for me

I still prefer your version, since that version is working fine, then there is a trick missing in your script

**Comment by riazXrazor** [comment] 2018-07-25 18:03
did u update ??

**Comment by ramojej** [comment] 2018-07-26 14:54
I updated and still having "Error occurred in login"

**Comment by kevenleone** [comment] 2018-07-26 14:57
Still working for me

**Comment by vitorpiovezam** [comment] 2018-08-01 14:50
"Error occurred in login" problem here too

**Comment by esculapio** [comment] 2018-08-01 22:32
Same problem here. "Error ocurred in Login"

**Comment by tenuke** [comment] 2018-08-04 01:55
Just worked few hours ago after the install , downloaded 1 course.
But now I cant log in. Logging in thru web browser works no problem.
There is no captcha or anything.. And it is the same computer im trying to use for the script
edit: ... and 5 minutes later UDL logs in again..

**Comment by utterly-calm** [comment] 2018-10-13 07:47
I'm getting this same issue. Just downloaded the latest package "npm i -g udemy-dl", also let us know if this can download udemy business accounts courses or not?

**Comment by utterly-calm** [comment] 2018-10-13 08:00
It suddenly worked, and again stopped working.

**Comment by c0ppo** [comment] 2018-10-13 08:50
I’ve mived on to udeler app. Works like a charm

—
Marin Knezovic

**Comment by riazXrazor** [comment] 2018-11-19 17:39
sorry everyone, was quite busy with ofc work and stuff, i hv pushed a fix, plz update and see if the issue is finally fix

**Comment by vikasnewports** [comment] 2018-11-25 12:16
@riazXrazor  login issue can not download it stuck 
after selection of Resolution or If I use UDL and input user email and passsword it stuck there

**Comment by riazXrazor** [comment] 2018-11-27 16:52
@vikasnewports which version are you using ?

**Comment by vikasnewports** [comment] 2018-11-28 14:56
@riazXrazor  , I am using very latest released by you.
and also I updated my query about Issue #40

**Closed as completed** 2019-01-19 19:08 UTC
Labels: Need Help
