### ISSUE TITLE
Can not login anymore

### ISSUE THREAD

**Issue by devrtk** [riazXrazor/udemy-dl#34] opened 2018-05-24 09:51 UTC
Please help to check, thanks bro!!!

**Comment by asonni** [comment] 2018-05-24 11:08
Same as me

**Comment by paulocmarques** [comment] 2018-05-24 11:41
Same as me

**Comment by riazXrazor** [comment] 2018-05-24 12:33
any error ??

**Comment by asonni** [comment] 2018-05-24 13:01
I got this error `[ERROR-152] Couldn't fetch token!`

**Comment by asonni** [comment] 2018-05-24 13:12
Just this error `◠ Logging in, please wait...          Cannot logging in`

**Comment by riazXrazor** [comment] 2018-05-24 14:29
it seems udemy.com has put up some addational security,
i hv pushed a fix and released a new version, update and check.

**Comment by asonni** [comment] 2018-05-24 16:44
Yes it works, thanks @riazXrazor 👍

**Comment by riazXrazor** [comment] 2018-05-24 16:59
your welcome 👍

**Comment by 211217613** [comment] 2018-05-24 17:01
Is that version 0.0.23? 

I'm getting the same error with version 0.0.23

**Comment by riazXrazor** [comment] 2018-05-24 17:04
@211217613 i jst checked its working fine, plz update properly

**Comment by bodaay** [comment] 2018-05-25 00:36
while it does work with the update, actually sometimes it doesn't. You have to wait for sometime until it works again. you can recreate the issue by trying to download a course. Stopping it, and restarting again multiple times. at some point it will completely stop and you cannot log in anymore, you will have to wait for sometime before you can login again

**Comment by riazXrazor** [comment] 2018-05-25 14:45
@bodaay ya i tied it, i am working on

**Comment by jrcribb** [comment] 2018-05-25 18:35
I have the same problem. Does you have an idea of what it's the cause?

**Comment by riazXrazor** [comment] 2018-05-26 10:14
its googles "are you human check" i think its triggered if an IP repetatly hits in a specific interval, for no the only solution is to wait for a while and try agian.

**Comment by bodaay** [comment] 2018-05-26 21:03
Thanks for the efforts, I think then it would be best to keep as it is for now, until you do the feature request and make it as GUI app, maybe using electron :). 
or as a quick hack, if there is a way when login fails, you open the browser by the script to login page, we login manually, then after submitting, session header data is copied to your script...

**Comment by ratanakpek007** [comment] 2018-05-26 23:09
for me it said "Can't login" and i had try another account, it is the error still

**Comment by tremkonzah** [comment] 2018-05-27 02:59
yeah me too, Cannot logging in

no other error in console :(

**Comment by vitorpiovezam** [comment] 2018-05-28 16:41
Same here, I've tried more than 10 times and only return errors.

**Comment by riazXrazor** [comment] 2018-05-28 16:51
When u hv failed login just wait for 10 minutes or so and then try again.
Although I am looking into it.

**Comment by razaqofficial** [comment] 2018-06-07 13:10
How do i update it?

**Comment by miguelcarrasco** [comment] 2018-06-08 21:09
Unfortunatly it's not working for me even if I wait several hours.

**Comment by riazXrazor** [comment] 2018-06-25 11:58
sorry guys, there is a captcha being returned, when the login api is being called, currently i am trying, no luck so far :(

**Comment by riazXrazor** [comment] 2018-07-24 09:35
hi guys, i hv push a fix and released a new version, plz can u check if the issue is fixed.

**Comment by riazXrazor** [comment] 2018-11-19 17:48
sorry everyone ws busy so couldnt work on it for some time,
push a fixed for this plz update.

**Closed as completed** 2019-01-19 19:10 UTC
Labels: Need Help
